name: Build and Deploy Node.js Project to Azure Function App - docprocessingfunc

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'docprocessingfunc'       # Your Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'             # Path to your Function App project
  NODE_VERSION: '20.x'                             # Node.js version

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm install

      - name: Build Project
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm run build --if-present

      - name: Run Tests
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm run test --if-present

      - name: Debug Build Output
        run: ls -R .  # Check all files generated in the build process

      - name: Zip Function App
        run: |
          cd dist                                     # Navigate into the 'dist' directory
          zip -r ../function-app.zip . -x "*.git*" "*.github*"  # Zip contents of 'dist' into 'function-app.zip'

      - name: Debug Zip File
        run: ls -la function-app.zip  # Ensure the zip file exists

      - name: Upload Deployment Package
        uses: actions/upload-artifact@v3              # Downgraded to v3 for GHES compatibility
        with:
          name: function-app                            # Consistent artifact name
          path: ./function-app.zip                     # Path to the zipped package

  deploy:
    runs-on: ubuntu-latest
    needs: build                                       # Ensure deploy runs after build

    steps:
      - name: Download Deployment Package
        uses: actions/download-artifact@v3            # Downgraded to v3 for GHES compatibility
        with:
          name: function-app                            # Must match the upload artifact name
          path: ./                                      # Destination path

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ./function-app.zip                    # Point to the correct zip file
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
