name: Build and Deploy Node.js Project to Azure Function App - docprocessingfunc

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'docprocessingfunc'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm install

      - name: Build Project
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm run build --if-present

      - name: Run Tests
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm run test --if-present

      - name: Debug Build Output
        run: ls -R .  # Check all files generated in the build process

      - name: Zip Function App
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r function-app.zip . -x "*.git*" "*.github*"

      - name: Debug Zip File
        run: ls -la function-app.zip  # Ensure the zip file exists

      - name: Upload Deployment Package
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: ./function-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Deployment Package
        uses: actions/download-artifact@v4
        with:
          name: function-app
          path: ./

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ./function-app.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
